### PR TITLE
Mpc 137 recording start and stop layout and app integration

### PR DESCRIPTION
**Pull request by fes7713**
Added clickable recording icon.
Added StateChangeListener to catch the change of states from Network code and Recording status update.
Added Recording endpoint in DB server.
Server endpoint integrated with app and users are able to control recording from button clicks

### CODE REVIEW

**Comment by fes7713** [comment]
Known issues 
- Video Listing does not work if you refresh page after start and stop recording because of converting stream files issues
Solution is found
- Use AWS EventBridge and convert video with AWS MediaConvert

**Review by JustinArd — APPROVED** [review]
Recording is a game-changer for the app. Nick Work!

**Comment by fes7713** [comment]
Current recording is buggy so I am introducing the new AWS stuff to automate stream video conversion to mp4 and retrieval without having DB (DB is too sloooow)

**Review by tuk12915 — APPROVED** [review]
This is really good bro

**Pull request merged**
